# Generated by Django 3.1.1 on 2021-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210213_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='target',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Referral', 'Referral'), ('Business_Partner', 'Business_Partner')], max_length=50),
        ),
    ]
