# Generated by Django 3.1.1 on 2021-02-16 08:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210216_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_Abtimage', models.ImageField(upload_to='images/')),
                ('aboutheading', models.CharField(max_length=50)),
                ('banner_carAboutImage', models.ImageField(upload_to='images/')),
                ('Aboutbody', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_heading', models.CharField(max_length=50)),
                ('banner_serv', models.ImageField(upload_to='images/')),
                ('Servicebody', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_Visimage', models.ImageField(upload_to='images/')),
                ('Vision_heading', models.CharField(max_length=50)),
                ('Visionbody', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='posthome',
            name='About_body',
        ),
        migrations.RemoveField(
            model_name='posthome',
            name='About_heading',
        ),
        migrations.RemoveField(
            model_name='posthome',
            name='Service_body',
        ),
        migrations.RemoveField(
            model_name='posthome',
            name='Service_heading',
        ),
        migrations.RemoveField(
            model_name='posthome',
            name='Vision_body',
        ),
        migrations.RemoveField(
            model_name='posthome',
            name='Vision_heading',
        ),
        migrations.RemoveField(
            model_name='posthome',
            name='banner_AboutImage',
        ),
        migrations.RemoveField(
            model_name='posthome',
            name='banner_Abtimage',
        ),
        migrations.RemoveField(
            model_name='posthome',
            name='banner_serv',
        ),
    ]
