# Generated by Django 3.1.7 on 2021-02-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210221_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='busiaddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='busiemail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='busimsg',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='busimobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='businame',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='busi_grp',
            new_name='Target',
        ),
        migrations.RenameField(
            model_name='refferal',
            old_name='refaddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='refferal',
            old_name='refemail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='refferal',
            old_name='refmsg',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='refferal',
            old_name='refmobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='refferal',
            old_name='refname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='refferal',
            old_name='ref_grp',
            new_name='Target',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stuaddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stuemail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stumsg',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stumobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stuname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='candi_grp',
            new_name='Target',
        ),
    ]
